version: "3"
services:
  users:
    build:
       context: . 
       dockerfile: Dockerfile.users
    image: users
    container_name: myusers
    ports:
      - "5001:5001"
    logging:
      driver: "json-file"
  todo:    
    build:
       context: .
       dockerfile: Dockerfile.todo
    image: todo
    container_name: mytodo
    ports:
      - "5002:5002"
